### ISSUE TITLE
It seems can not Reuse the HttpClient instance

### ISSUE THREAD

**Issue by frankmeten** [taliox/zulip-java-rest#1]
```
for (int i = 1; i < 6; i++) {
			ZulipRestExecutor  executor = new ZulipRestExecutor(user, apikey,zuliphost);
			postMessage.setTo("user0" + i + "@myzulip.com");
			postMessage.setContent("loop " + i + "hello , current time is " + getNowTime());
			String response2 = executor.executeCall(postMessage);
			System.out.println(response2);
		}
```
will work, but it not reuse the HttpClient instance

```
ZulipRestExecutor  executor = new ZulipRestExecutor(user, apikey,zuliphost);
for (int i = 1; i < 6; i++) {
			postMessage.setTo("user0" + i + "@myzulip.com");
			postMessage.setContent("loop " + i + "hello , current time is " + getNowTime());
			String response2 = executor.executeCall(postMessage);
			System.out.println(response2);
		}
``` 
this will not work, it stuck after loop 2 times

**Comment by raLaaaa** [comment]
Hey, thanks for reporting this issue!
I could locally reproduce it and fix it for myself. 

Could you check and see if the bug is fixed for you by the newest commit? If yes the new version will be deployed on maven next week.

**Comment by frankmeten** [comment]
> Hey, thanks for reporting this issue!
> I could locally reproduce it and fix it for myself.
> 
> Could you check and see if the bug is fixed for you by the newest commit? If yes the new version will be deployed on maven next week.

Thanks for reply rapidly.
It works!
