### ISSUE TITLE
Readme missing variable name when creating executor

### ISSUE THREAD

**Issue by JonathanLindsey** [taliox/zulip-java-rest#2]
In the readme, shouldn't the line
`ZulipRestExecutor  = new ZulipRestExecutor("user@zulip.com", "apikey","https://zulip.example.com/");`
have the variable name `executor` so it would actually be
`ZulipRestExecutor executor = new ZulipRestExecutor("user@zulip.com", "apikey","https://zulip.example.com/");`
?

Also, is there an import needed?

When I compile this code on https://repl.it/languages/java10 after installing the io.taliox:zulip-java-rest package it gives this terminal output.
Code:
```
class Main {
  public static void main(String[] args) {
    ZulipRestExecutor executor = new ZulipRestExecutor("user@zulip.com", "apikey","https://zulip.example.com/");
  }
}
```
Terminal output:
```
 javac -classpath .:/run_dir/junit-4.12.jar:target/dependency/* -d . Main.java
Main.java:3: error: cannot find symbol
    ZulipRestExecutor executor = new ZulipRestExecutor("user@zulip.com", "apikey","https://z
ulip.example.com/");
    ^
  symbol:   class ZulipRestExecutor
  location: class Main
Main.java:3: error: cannot find symbol
    ZulipRestExecutor executor = new ZulipRestExecutor("user@zulip.com", "apikey","https://z
ulip.example.com/");
                                     ^
  symbol:   class ZulipRestExecutor
  location: class Main
2 errors
compiler exit status 1

```

**Comment by raLaaaa** [comment]
Hey, thanks for the hint! You are right the readme is missing the variable name.
I'll adapt that :)

You indeed need to import the library. The terminal output you pasted hints that the library is not correctly imported.
`import io.taliox.zulip.ZulipRestExecutor;` should fix that.

**Comment by JonathanLindsey** [comment]
Thanks, that import helped! However, when I added the code to send a message it does not compile again. Of course I understand it won't send the message until I fill in my API key, stream and such but it should at least compile. Do I need another import line? I already tried `import io.taliox.zulip.PostMessage;` and `import io.taliox.zulip.*;`

Sorry for the newbie questions.

BTW you made a small typo in your commit this morning of the spelling of executor.


Code:
```
import io.taliox.zulip.ZulipRestExecutor;

class Main {
  public static void main(String[] args) {
    ZulipRestExecutor executor  = new ZulipRestExecutor("user@zulip.com", "apikey","https://zulip.example.com/");

    PostMessage postMessage = new PostMessage("streamname", "topicname", "hello world");
    String response = executor.executeCall(postMessage);
  }
}
```
Terminal output:
```
 javac -classpath .:/run_dir/junit-4.12.jar:target/dependency/* -d . Main.java
Main.java:7: error: cannot find symbol
    PostMessage postMessage = new PostMessage("streamname", "topicname", "hello world");
    ^
  symbol:   class PostMessage
  location: class Main
Main.java:7: error: cannot find symbol
    PostMessage postMessage = new PostMessage("streamname", "topicname", "hello world");
                                  ^
  symbol:   class PostMessage
  location: class Main
2 errors
compiler exit status 1

```

**Comment by raLaaaa** [comment]
I guess I shouldn't do things in a hurry, fixed it.

You have to do `import io.taliox.zulip.calls.messages.PostMessage;` to access this class.

**Comment by raLaaaa** [comment]
I'm assuming you could fix it. I'll cose this issue.

**Comment by JonathanLindsey** [comment]
That is fine. Thank you.

Just for your information this explains why `import io.taliox.zulip.*;` doesn't work.
https://stackoverflow.com/questions/18245483/recursive-import-java
