### ISSUE TITLE
Delete and rename?

### ISSUE THREAD

**Issue by JonCSgr** [taliox/zulip-java-rest#3]
Hey , is there a delete Stream and rename stream function because i can't seem to find it .

Also im struggling a bit like i want to subscribe a user to a stream and i am trying this code
   PostSubscription subscribe = new PostSubscription("[{\"name\":\"A new Stream\"}]");

        subscribe.setInvite_only(true);
        subscribe.setPrincipals("user10@example.org");
        executor.executeCall(subscribe);

And im getting an error , would u mind help me out? Thanks in advance.

**Comment by raLaaaa** [comment]
Hey, could you show me you error? That would be helpful.

I think you are right currently the wrapper does not provide the possibility to update or delete streams. 
I might add that in the future if I find time for that.

**Comment by JonCSgr** [comment]
Hey my bad here it is https://prnt.sc/vozjyn
Also since i need to use rename and delete i may try to develop them and of course share them with you , do u have any guide how to work with it since i never developed an API before (just graduated :P )

**Comment by raLaaaa** [comment]
Do you mind showing your JSON code? Looks like it's invalid.

Sure feel free to. Just fork the repository and add a class for updating / deleting streams in the stream package. 
When looking at other files in that package I think it should be more or less self explanatory to add these :)

**Comment by JonCSgr** [comment]
Hey again , i think i am doing something really wrong in either adding attributes or in the parameters, here is the full code i am using
https://prnt.sc/vp1cxz

**Comment by raLaaaa** [comment]
I think the problem is that your principals is not valid JSON. Therefore your Zulip server cant interpret your parameters.
Could you checkout this page to get the correct format?

https://zulip.com/api/subscribe

**Comment by JonCSgr** [comment]
ok gotcha , sorry im still newbie . Figured it out . Will try to implement rename and delete

**Comment by raLaaaa** [comment]
No problem! Dont hesitate to ask if you got problems.
